version: "3.1"
services:
  php:
    image: ricardopedias/docker-project:php82
    container_name: iquety-prospection
    volumes:
      - .:/application
    networks:
      - iquety-prospection-network
  mysql:
    image: ricardopedias/docker-project:mysql80
    container_name: iquety-prospection-mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=devel
      - MYSQL_DATABASE=devel
      - MYSQL_USER=devel
      - MYSQL_PASSWORD=devel
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "8081:3306"
      - "8082:80"
    networks:
      - iquety-prospection-network
  redis:
    image: redis:alpine
    container_name: iquety-prospection-redis
    restart: always
    ports:
      - "8083:6379"
    networks:
      - iquety-prospection-network
networks:
networks:
  iquety-prospection-network:
    driver: bridge